mysociety/open311-adapter

- cpanfile
- cpanfile.snapshot
- vendor/bin/carton
A few packages need upgrading due to `.` not being in `@INC` any more.
(not sure if the entire `cpanfile.snapshot` diff is required, it seems like a lot of stuff got removed?)
> Perl 5.24 compatibility

- perllib/Integrations/Confirm.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- perllib/Open311/Endpoint/Service/Attribute.pm
- perllib/Open311/Endpoint/Service/Request/Update/mySociety.pm
- script/test
- t/open311/endpoint.t
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm.yml
Some improvements to the Confirm integration:
- Subclasses can specify a default `SiteCode` if it's not passed in as a service request attribute.
- The Confirm enquiry's `StatusCode` is exposed as `external_status_code` in `/servicerequestupdates.xml` output (to allow FMS to trigger response templates based on its value).
- Correctly handle optional `singlevaluelist` attributes that are sent from FMS with an empty value.
Fixes #11.
> Default site code, external status codes and empty attributes

- .travis.yml
- perllib/Open311/Endpoint/Integration/Confirm.pm
Fetched enquiries were being presented with the original logged time
as their created & last updated values. This meant FMS was ignoring
reports which were recently updated but opened before the 1-hour window
when fetching reports.
The enquiry fetching code could do with some tests, but after battling for too long to get it working I wanted to get this fix deployed to stop the cron emails.
Fixes mysociety/fixmystreet-commercial#1143.
> [Confirm] Set requested_/updated_datetime of fetched requests correctly

- perllib/Open311/Endpoint/Integration/WDM.pm
- t/open311/endpoint/oxfordshire.t
When fetching comments the serice_request_id and the customer_reference
are the wrong way round so swap them over if it looks like an old
request. And do not pass a customer_reference because we don't want to
set that on old enquiries initially.
> [OCC] handle incorrect IDs in old comment updates

- perllib/Open311/Endpoint/Integration/Confirm.pm
The Confirm call to GetEnquiryStatusChanges filters on LoggedTime, and
it's possible for returned Enquiries to have a LogEffectiveTime outside
of the start/end times. Using LoggedTime instead of LogEffectiveTime as
the updated_datetime field for fetched requests ensures the values are
within the requested parameters.
> Use LoggedTime, not LogEffectiveTime, for fetched requests

- perllib/Open311/Endpoint/Integration/SalesForce.pm
- t/open311/endpoint/rutland.t
we use md5 hashes as part of the update id and Digest::MD5 does not like
unicode strings so we have to encode them as bytes before passing in to
md5_hex
> [Rutland] fix issue with unicode characters in updates

- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- perllib/Open311/Endpoint/Service/Request/CanBeNonPublic.pm
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm_private.yml
If `fetch_reports_private` is set in the config file then include a `non_public` field set to 1 in the XML returned by `get_service_requests`.
> Allow setting all fetched reports to be marked private in Confirm integrations

- perllib/Open311/Endpoint/Integration/Confirm.pm
- t/open311/endpoint/confirm.t
Sometimes confirm includes microseconds in datetimes which fails the
validator so truncate all datetimes to seconds.
> [Confirm] truncate all times to seconds

- perllib/Open311/Endpoint/Integration/SalesForce.pm
- t/open311/endpoint/rutland.t
Because we don't have a way to limit requests by date ignore those that
are older than the start date as they will only be rejected by
FixMyStreet anyway. Also means we avoid the calls to fetch service
details for those requests.
> [Rutland] ignore reports older than start date

- perllib/Open311/Endpoint/Integration/Alloy.pm
- t/open311/endpoint/alloy.t
- t/open311/endpoint/json/alloy/inspect_search.json
- t/open311/endpoint/json/alloy/resource_3027029_v272125.json
- t/open311/endpoint/json/alloy/resource_3027030_v271881.json
- t/open311/endpoint/json/alloy/resource_versions_3027030.json
In order to check if the customer comments has changed we need to fetch
the previous version and compare the two, and only if they are different
do we set the description. Otherwise once customer comments is set we'll
display an update on FMS for every change in Alloy.
> [Alloy] only set description if customer comments changes

- conf/council-bexley.yml-example
- perllib/Open311/Endpoint/Integration/Symology.pm
- t/open311/endpoint/bexley.t
Bexley updates will be coming from 2 CSVs, not one. This adjusts the code to read both, work out automatically the headers rather than bind fixed ones, etc.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1366
> [Bexley] Fetch more than one CSV file.

- perllib/Open311/Endpoint/Integration/Symology.pm
- t/open311/endpoint/bexley.t
Sometimes Bexley give a warning but still create the record. They don't allow resubmission of a created record, so in that case we should tell FMS that the report has been sent.
> Do not die on failure if record created.

- .travis.yml
- bin/confirm-upload
- conf/council-hounslow_confirm.yml-example
- conf/crontab-example
- perllib/Integrations/Alloy/Northamptonshire.pm
- perllib/Integrations/Confirm.pm
- perllib/Integrations/Confirm/BANES.pm
- perllib/Integrations/Confirm/Buckinghamshire.pm
- perllib/Integrations/Confirm/Hounslow.pm
- perllib/Integrations/Confirm/Lincolnshire.pm
- perllib/Integrations/WDM/Oxfordshire.pm
- perllib/Open311/Endpoint.pm
- perllib/Open311/Endpoint/Integration/UK.pm
- perllib/Open311/Endpoint/Integration/UK/Hounslow.pm
- perllib/Open311/Endpoint/Role/ConfigFile.pm
- t/open311/endpoint/confirm_upload.t
WIP Confirm integration for Hounslow.
New features:
- Allow files to be uploaded directly to Confirm instead of just linking to FMS
- Services can be marked as private using Open311 keywords
> Hounslow Confirm integration

- cpanfile
- cpanfile.snapshot
- perllib/Open311/Endpoint/Integration/Confirm.pm
- t/open311/endpoint/confirm.t
When fetching reports from Confirm to display on FMS we don't want to include those which don't have a location. Previously open311-adapter didn't include in the `GET /requests.xml` output any Enquiries that didn't have an `EnquiryX` & `EnquiryY` defined. However some Confirm instances set those values to `0` which meant they were being passed through to FMS.
> [Confirm] Don’t output reports with 0/0 easting/northing

- perllib/Open311/Endpoint/Integration/Alloy.pm
- t/open311/endpoint/alloy.t
- t/open311/endpoint/alloy.yml
- t/open311/endpoint/json/alloy/defect_search.json
- t/open311/endpoint/json/alloy/inspect_search.json
- t/open311/endpoint/json/alloy/resource_3027031_v271883.json
- t/open311/endpoint/json/alloy/resource_versions_3027031.json
We need to set this to stop phantom updates being produced. This
happens because when an inspection is closed it always sets an
external_status_code which we never unset. Then when updates arrive
from defects with no external_status_code the template fetching code at
FixMyStreet sees that the external_status_code has changed and fetches
the template. This means we always get an update even if nothing has
changed. So, set the external_status_code on defects associated with an
inspection to the external_status_code used when an inspection is marked
for raising as a defect.
> [Northamptonshire] always set external_status_code on defect updates

- perllib/Open311/Endpoint/Integration/Confirm.pm
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm.yml
Allow categories to be under more than one group in the whitelist. Only
one services entry per category is generated but it will include all the
groups in the group tag.
> [Confirm] allow categories to exist in multiple groups

- perllib/Open311/Endpoint.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Schema.pm
- perllib/Open311/Endpoint/Service.pm
- t/open311/endpoint/confirm.t
This seems nicer than CSV :)
Confirm will always use `groups`, others will continue to use group.
> Add new <groups> output for multiple groups.

- perllib/Open311/Endpoint/Integration/Alloy.pm
- t/open311/endpoint/json/alloy/resource_3027030_v271881.json
use `usedSystemVersionId` instead of `resourceSystemVersionId`.
> [Alloy] change the version id we use for updates numbers

- perllib/Open311/Endpoint/Integration/Confirm.pm
Ensures any existing groups in `wrapped_services` in the YML config are included in the output. Also allows a wrapped service to appear in multiple groups by setting the `group` value to a list instead of a string.
> [Confirm] Output <groups> correctly for wrapped_services

- t/open311/endpoint/bexley_confirm.t
- t/open311/endpoint/bexley_confirm.yml
This tests that the list of services is correctly returned from the Bexley Confirm adapter.
This has mostly been copied from `t/open311/endpoint/confirm.t` and then slimmed down to just have the bits to test the GET services call. I must admit that the `$open311->mock(perform_request => sub {…` part is a bit of a mystery to me, for now I've just copy/pasted it in to get things working, so there's a fair bit of duplication at the moment.
Also the `*::Dummy` packages seem to be performing overlapping duties as they're both setting the config file name, but again I've just copied them in and adjusted them to be Bexley-Confirm-specific for now.
Any and all feedback welcome!
As a council I want users to be able to select from a list of problem categories.
Fixes …
> [Bexley Confirm] Add test for getting the list of services

- perllib/Integrations/WDM.pm
- perllib/Open311/Endpoint/Integration/Alloy.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Integration/SalesForce.pm
- perllib/Open311/Endpoint/Integration/UK/Northamptonshire.pm
- perllib/Open311/Endpoint/Integration/WDM.pm
- t/open311/endpoint/alloy.t
- t/open311/endpoint/confirm.t
Make service_request_content always a function, which then means
we can improve a couple of test files to test their integrations
directly, rather than via the main UK one, so then we can remove
unneeded jurisdiction_id functions.
> Remove unneeded test gubbins.

- perllib/Open311/Endpoint/Integration/Confirm.pm
- t/open311/endpoint/confirm_upload.t
- t/open311/endpoint/confirm_wrapped.t
Otherwise FixMyStreet is constantly updating extra fields with order
changes.
> [Confirm] Maintain attribute order in wrapped services.

- conf/council-bexley_confirm_grounds.yml-example
- conf/council-bexley_confirm_trees.yml-example
- perllib/Integrations/Confirm/BexleyGrounds.pm
- perllib/Integrations/Confirm/BexleyTrees.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/ConfirmGrounds.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/ConfirmTrees.pm
- t/open311/endpoint/bexley.t
- t/open311/endpoint/bexley_confirm.t
Bexley have two separate Confirm servers, one for trees and one for grounds. This change splits the Bexley Confirm integration in two so we can have one integration for each server.
There aren't separate tests for the trees and grounds integrations, since the implementations are virtually identical. I spoke to @dracos about this and we agreed that if/when the implementations diverge we can add tests at that point.
Related to https://github.com/mysociety/fixmystreet-commercial/issues/1568 and https://github.com/mysociety/fixmystreet-commercial/issues/1573 (since we need separate category and status mappings for the trees and grounds servers).
> [Bexley Confirm] Split into two separate integrations - trees and grounds

- conf/council-peterborough_confirm.yml-example
- perllib/Integrations/Confirm.pm
Peterborough only want customer details associated with the `EnquiryCustomer` record, not the `ContactName`/`ContactEmail`/`ContactPhone` fields on enquiries. This PR adds a config option to allow that behaviour.
> [Confirm] Add option to not set ContactName/Email/Phone when raising enquiries

- perllib/Open311/Endpoint/Integration/Confirm.pm
- t/open311/endpoint/confirm_attributes.t
One service we connect to sends through option text with number prefixes, which we wish to remove before display.
> [Confirm] Allow override of attribute option names.

- .gitignore
- conf/logrotate-example
Example configuration for rotating the log file, together with some additions to `.gitignore` for deployed files.
> Add a logrotate example configuration file

- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley.pm
- t/open311/endpoint/bexley.t
I don't think anything uses this, and can't now recall how I realised it wasn't doing it, but I guess if a backend request ID is included in the response, it should be mapped to have the prefix like the update ID>
> [Bexley] Make sure service request ID updated on updates.

- perllib/Open311/Endpoint/Integration/Multi.pm
- perllib/Open311/Endpoint/Integration/UK.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley.pm
We want to reuse this code for Peterborough, so extract it from Bexley and create a generic Multi backend.
This allows a council to have more than one backend, and handles calling them all and combining the results, as well as sending reports to the correct backend.
Part of the Peterborough ezytreev integration work.
> Extract multiple children integration from Bexley

- perllib/Integrations/Alloy.pm
- perllib/Integrations/Confirm.pm
- t/open311/endpoint/alloy.t
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm_attributes.t
- t/open311/endpoint/confirm_upload.t
- t/open311/endpoint/confirm_wrapped.t
- Fixes a bug where tests would fail due to earlier tests' Confirm data being cached
- Ensures tests use a prefixed namespace to prevent overlap with running open311-adapter instance
> Improve interaction between tests and memcached

- conf/council-peterborough_ezytreev.yml-example
- perllib/Open311/Endpoint/Integration/Ezytreev.pm
- perllib/Open311/Endpoint/Integration/UK/Peterborough.pm
- perllib/Open311/Endpoint/Integration/UK/Peterborough/Confirm.pm
- perllib/Open311/Endpoint/Integration/UK/Peterborough/Ezytreev.pm
- t/open311/endpoint/uk.t
This switches Peterborough to the new "multi" integration which was extracted from Bexley in #81, and then adds ezytreev integration, which was added in #85.
Part of [Peterborough Phase 2 - EzyTreev](https://github.com/mysociety/fixmystreet-commercial/milestone/37).
> [Peterborough] Ezytreev integration

- perllib/Open311/Endpoint/Integration/Ezytreev.pm
- t/open311/endpoint/ezytreev.t
Previously we only got the latest update for an enquiry, which meant if someone had changed the status multiple times before closing the enquiry modal in ezytreev we'd only get the latest status.
Ezytreev have now added a "StatusHistory" field to the API which contains a full list of updates, along with a unique ID for each one, so we can use that to ensure we don't miss any updates.
Follows on from #87
> [Ezytreev] Use new StatusHistory field for full updates

- perllib/Open311/Endpoint/Integration/Ezytreev.pm
- t/open311/endpoint/ezytreev.t
This allows us to setup response templates in the admin which are triggered by specific external status codes.
> [Ezytreev] Include external_status_code in updates

- conf/council-peterborough_ezytreev.yml-example
- perllib/Open311/Endpoint/Integration/Ezytreev.pm
- t/open311/endpoint/ezytreev.t
We want to pass the update notes for certain status codes through to FMS. This change adds a whitelist of codes that we allow the notes for and then checks that list when retrieving updates and shows the notes if it's in the whitelist, otherwise it just shows the enquiry status description.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1752
> [Ezytreev] Get update notes for certain status codes

- perllib/Open311/Endpoint/Integration/Ezytreev.pm
- t/open311/endpoint/ezytreev.t
When an enquiry is attached to an order item it results in two status updates being generated for one status code. Ignore the update that has the order item ID in it, since this ID will be meaningless to the user anyway.
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1753
> [Ezytreev] Ignore duplicate status updates

- perllib/Open311/Endpoint/Integration/Ezytreev.pm
These are producing random re-openings at the moment where an unmapped status code that FMS doesn't need to worry about is used. Rather than re-opening the report we just want to ignore the update.
Part of https://github.com/mysociety/fixmystreet-commercial/issues/1780
> [Ezytreev] Ignore updates with unmapped status codes

- perllib/Integrations/WDM.pm
- perllib/Open311/Endpoint/Integration/WDM.pm
- t/open311/endpoint/oxfordshire.t
- t/open311/endpoint/oxfordshire.yml
add a status_map key to the config and use that to map from WDM statuses
in fetched updates to FixMyStreet statuses
> [WDM] enable statuses to be mapped

- perllib/Open311/Endpoint/Integration/SalesForceRest.pm
- t/open311/endpoint/eastsussex.t
- t/open311/endpoint/eastsussex.yml
- t/open311/endpoint/services.json
Some of the internal Salesforce names aren't especially user facing so
allow them to be renamed on the way out and then reversed on the way
back in
> [EastSussex] allow groups to be renamed for display

- perllib/Open311/Endpoint/Integration/SalesForceRest.pm
- t/open311/endpoint/eastsussex.t
- t/open311/endpoint/eastsussex.yml
- t/open311/endpoint/services.json
Some service names appear under multiple groups but we don't want to
display all of them. Add a blacklist that filters out groups from
services.
> [EastSussex] filter groups at a service level

- perllib/Open311/Endpoint/Integration/Bartec.pm
- t/open311/endpoint/bartec.t
- t/open311/endpoint/xml/bartec/servicerequests_get_SR5.xml
- t/open311/endpoint/xml/bartec/servicerequests_updates_get_20200622.xml
Factor out the service request name generating code so we can use it to
make sure service requests with mapped categories get the correct name.
And use the existing code to check for allowed categories for the same
reason.
> [Bartec] correctly map fetched requests catgories

- perllib/Open311/Endpoint/Service/UKCouncil/Oxfordshire.pm
- t/open311/endpoint/oxfordshire.t
small change to handle the feature_id asset we're now using now that we have assets.
> [Oxfordshire] ignore new feature_id attribute

- perllib/Open311/Endpoint/Integration/UK/NorthamptonshireAlloyV2.pm
No longer seems to be required and causes genuine updates to be skipped.
> [Northamptonshire] remove special update skipping code

- perllib/Open311/Endpoint/Integration/Bartec.pm
- t/open311/endpoint/bartec.t
This works around a bug in Bartec that meant we were missing updates on reports.
See the comment in the code for more details.
> [Bartec] Fix issue fetching updates

- bin/alloy_v2_get_inspection_changes.pl
Script that takes an alloy itemId for an inspection or defect and prints
out the history of status changes. If you pass in an inspection id it
will also get the history of the related defect.
> [Alloy] utility script to get inspection status history

- perllib/Open311/Endpoint/Integration/UK/CentralBedfordshire.pm
- t/open311/endpoint/centralbedfordshire.t
A simple change as Central Beds Symology doesn't require a different code for each status.
> [Central Beds] Add sending of updates

- perllib/Open311/Endpoint/Integration/Symology.pm
- t/open311/endpoint/bexley_symology.t
- t/open311/endpoint/centralbedfordshire.t
This means we can potentially filter out non-FMS reports when fetching updates to hopefully speed things up a bit.
> [Symology] Config to add a prefix to external ID when sending to Symology

- perllib/Integrations/Bartec.pm
- perllib/Open311/Endpoint/Integration/Bartec.pm
- t/integrations/bartec.t
- t/open311/endpoint/bartec.t
- t/open311/endpoint/bartec.yml
- t/open311/endpoint/xml/bartec/servicerequests_types_get.xml
- Makes it possible to add keywords to Open311 service definitions in the YAML config
- Puts Bartec endpoint URLs in config for easier local debugging/testing
> [Bartec] Add per-service Open311 keywords

- perllib/Integrations/Echo.pm
- t/open311/endpoint/echo.t
The previous fix for this in Symology was the not-great-commit-message cac33c510274a6fc7ab5801d4f8e847bda906973, but I wasn't sure if any other types were being used here (e.g. integers being sent as integers), so thought it easier just to disable base64 encoding as an output instead, otherwise leaving the normal detection alone.
> [Echo] Prevent encoding of string values.

- perllib/Open311/Endpoint/Integration/UK/Bexley.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/ConfirmGrounds.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/ConfirmTrees.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/Symology.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/Uniform.pm
- perllib/Open311/Endpoint/Role/BexleyPrivateComments.pm
- perllib/Open311/Endpoint/Service/UKCouncil/BexleyConfirm.pm
- perllib/Open311/Endpoint/Service/UKCouncil/BexleySymology.pm
- perllib/Open311/Endpoint/Service/UKCouncil/BexleyUniform.pm
- t/open311/endpoint/bexley_private_comments.t
- t/open311/endpoint/bexley_symology.t
This is to work with the changes at the FixMyStreet end to send private comments over when they are entered on the report form.
I tried putting the `sub _build_attributes` bit into the `BexleyPrivateComments` role, but you can't use the `SUPER` pseudo-class from a role because it refers to the package rather than the object ([source](https://perldoc.perl.org/perlobj#How-SUPER-is-Resolved)).
The FixMyStreet bits are in https://github.com/mysociety/fixmystreet/pull/3222
Part of https://github.com/mysociety/fixmystreet-commercial/issues/1850
> [Bexley] Handle private comments field

- perllib/Integrations/Echo.pm
- t/open311/endpoint/northamptonshire_alloy.t
The Echo change to SOAP 1.2 was infecting other SOAP clients.
> Fix SOAP version issue

- perllib/Integrations/Alloy.pm
- perllib/Integrations/AlloyV2.pm
- perllib/Integrations/Bartec.pm
- perllib/Integrations/Confirm.pm
- perllib/Integrations/SalesForceRest.pm
- perllib/Role/Memcached.pm
Mostly for the middle commit which had me very confused yesterday as to why one test, run by itself, was seeing a completely different test's service whitelist.
Fixes #113 (I think the namespace would have to be given once per config file it applies to, rather than centrally, as Integrations::* all have their own config files attached, but that probably doesn't matter?)
> Memcached improvements

- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/echo.t
Override the default client reference for an event if there is a
client_reference attribute in the request.
> [Echo] allow client reference to be customised

- perllib/Open311/Endpoint/Integration/Ezytreev.pm
- perllib/Open311/Endpoint/Integration/Symology.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/Symology.pm
- perllib/Open311/Endpoint/Integration/UK/CentralBedfordshire.pm
- perllib/Open311/Endpoint/Integration/Uniform.pm
- perllib/Role/EndpointConfig.pm
- t/open311/endpoint/bexley_symology.t
- t/open311/endpoint/bexley_symology.yml
- t/open311/endpoint/bexley_uniform.t
- t/open311/endpoint/centralbedfordshire.t
- t/open311/endpoint/ezytreev.t
- t/open311/endpoint/uniform.t
This partially reverts commit c55f7eed9. Web::Simple::Application has an attribute called `config`, so we cannot use that in a subclass, as it has already been set. Even if it didn't, I'm not sure anything was actually setting config_filename in these classes to be used.
The test move to use a yml file rather than mock config directly would be enough to catch the first of these, because config was then not set at all when running the test.
> Switch O::E::I:: config to endpoint_config.

- perllib/Integrations/Bartec.pm
- perllib/Open311/Endpoint/Integration/Bartec.pm
- t/open311/endpoint/bartec.t
- Make sure report content is properly escaped
- Stop report sending requests failing after Bartec ServiceRequest has been created, leading to duplicate reports being raised.
For https://github.com/mysociety/societyworks/issues/2391
> [Bartec] Improve report sending resilience

- perllib/Open311/Endpoint/Integration/Echo.pm
don't include the user's email if contributed_as is set to
anonymous_user
> [Echo] ignore emails on anonymous reports

- perllib/Integrations/Confirm.pm
- perllib/Integrations/Symology.pm
- perllib/Integrations/Uniform.pm
Remove some hard coded SOAP headers which were causing integrations to
send SOAP requests with headers for the the wrong version and causing
415 errors.
> fix SOAP version issues resulting in media type errors

- perllib/Integrations/SalesForce.pm
- perllib/Open311/Endpoint/Integration/SalesForce.pm
- t/open311/endpoint/rutland.t
This uses Rutland's new FixMyStreetInfoV2 endpoint which now has extra fields for specifying parent-child relationships.
The `parent` field indicates the parent category, AKA the group of the service.
There is also a `hasChildren` field which when set to "true" (string) indicates that the entry is a group and shouldn't be queried for attributes.
Part of https://github.com/mysociety/fixmystreet-commercial/issues/2206
> [Rutland] Add support for getting category groups from Salesforce

- perllib/Integrations/SalesForce.pm
- perllib/Open311/Endpoint/Integration/SalesForce.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Rutland.pm
- t/open311/endpoint/rutland.t
Rutland's Salesforce now includes an `html` field on categories and groups which Rutland want to display on the FMS front end. This change puts the HTML from Salesforce for both the category and the category's group into the service's attributes so that FMS can pull it out at the other end.
The PR to output this text on FixMyStreet is here: https://github.com/mysociety/fixmystreet/pull/3434.
Part of https://github.com/mysociety/societyworks/issues/2206
I originally tried doing this with new top-level elements, but that didn't quite feel right and broke lots of tests. So I went with putting it in the attributes in the end, even though it doesn't feel _quite_ right. You can see the code I wrote for that here: https://github.com/mysociety/open311-adapter/compare/rutland-salesforce-groups-supp …
> [Rutland] Pass through Salesforce HTML hint text in attributes

- perllib/Open311/Endpoint/Integration/Symology.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/Symology.pm
- t/open311/endpoint/bexley_symology.t
Use the Event Type column as the external status code if present in the
update CSV.
Fixes mysociety/fixmystreet-commercial#2279
> [Bexley] use Symology Event Type as external status

- bin/get_salesforce_credentials.pl
- perllib/Open311/Endpoint/Integration/SalesForce.pm
- t/open311/endpoint/rutland.t
"’" in fetched update text was causing "Wide character in subroutine entry" errors
> [Salesforce] Fix update fetching with rich quotes

- perllib/Open311/Endpoint/Integration/UK.pm
This data is currently held over NFS and we were seeing stuck flock calls.
These files are not written to, only read or removed, and the script only
runs on one server anyway, it would still have a race condition if run on
more than one even with shared locking.
> [Confirm] Remove file locking.

- perllib/Integrations/Confirm.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- t/open311/endpoint/confirm_attributes.t
- t/open311/endpoint/confirm_date.t
Needs test for sending enquiries to Confirm. Might need some counterpart on FMS too.
> [Confirm] Use ‘datetime’ attribute type for date fields in Confirm

- perllib/Open311/Endpoint/Integration/Confirm.pm
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm.yml
Fixes https://github.com/mysociety/societyworks/issues/2797 (once config is updated, see below).
Current live config has one issue without this, in that it has two `RM_FLO` but only one gets created.
Adapted config for changes currently inactive in live would be:
```
Trees:
RM_TREE_1: Dead/diseased tree
RM_TREE_2: Other tree issue
RM_TREE_3: Overhanging branch/tree
RM_TREE_4: Tree roots raising a footpath
RM_TREE_5: Tree stumps
SLRM_SLD_tree: Tree blocking a street light
ITS_SMP_tree: Tree blocking traffic signal/sign
```
> [Confirm] Allow _extra on whitelist codes to work and map to same Confirm service/subject

- perllib/Integrations/Confirm.pm
- perllib/Integrations/SalesForce.pm
- perllib/Open311/Endpoint.pm
- t/open311/endpoint.t
- t/open311/endpoint/Endpoint1.pm
- t/open311/endpoint/confirm.t
- t/open311/endpoint/rutland.t
Previously this was only set on the Echo integration (see https://github.com/mysociety/open311-adapter/commit/706644b47883c57e0373ca4e27559cc0088e0c4b), but this is probably a sensible default generally, in the spirit of being liberal with what you receive.
I'm printing out a warning to the logfile if an attribute is unrecognised, but these are suppressed if the service has the allow_any_attributes flag set.
This is a roundabout way of fixing the error that Bucks is getting on staging currently, as that's an issue with the new grass cutting question not being recognised.
The change to `.github/workflows/default.yml` was necessary because calling methods on `$self->logger` fails without a `conf/general.yml` present.
> Allow any service attribute through by default

- cpanfile
- perllib/Integrations/Confirm.pm
- t/open311/endpoint/confirm.t
Fixes https://github.com/mysociety/open311-adapter/issues/204.
This fix prevents the entire upload of a report from being marked as a failure if the initial report creation succeeds but the later document upload fails.
> Wrap Confirm document storage in an eval

- bin/centralbeds/fetch_symology_csv
- conf/packages
curl is not working on the new server, returning a 79 (SSH) error.
> [Central Beds] Replace curl with sftp.

- perllib/Integrations/Confirm.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Integration/UK.pm
- perllib/Open311/Endpoint/Integration/UK/Lincolnshire.pm
- perllib/Open311/Endpoint/Role/CompletionPhotos.pm
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm.yml
- t/open311/endpoint/lincolnshire.t
Adds a new ‘completion_statuses’ config key which controls when Confirm should be queried for a job completion photo when fetching Open311 updates.
Changes from when you wrote it: Removed memcached code, removed login token code (oauth works), tidied up API call functions and moved bits round, made Lincolnshire-specific function, added tests.
Have tested locally with both production and development, and appears to work :)
> [Confirm] Include completion photo in update.

- conf/council-hackney_environment_alloy_v2.yml-example
- conf/council-hackney_highways_alloy_v2.yml-example
- conf/council-northamptonshire_alloy_v2.yml-example
- conf/council-oxfordshire_alloy_v2.yml-example
- perllib/Integrations/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- t/open311/endpoint/alloyv2.yml
- t/open311/endpoint/alloyv2_ncc.yml
- t/open311/endpoint/oxfordshire_alloy.yml
New keys have been fetched, so would need putting in server config as this was deployed.
Fixes https://github.com/mysociety/open311-adapter/issues/208
> [Alloy] Use new key method

- conf/council-sutton_echo.yml-example
- perllib/Open311/Endpoint/Integration/Echo.pm
- perllib/Open311/Endpoint/Integration/UK/Sutton.pm
- t/open311/endpoint/sutton.t
- t/open311/endpoint/sutton.yml
- t/open311/endpoint/uk.t
This is an empty Echo endpoint, apart from adding `service_mapping` as the FMS end is using (and passing through to here) Task IDs, not service IDs which we then need to send to Echo; and a little bit of code to set the right booleans in the missed collection events depending on what comes in (this is awaiting confirmation from them but might as well go up as is).
> [Sutton] Add endpoint.

- perllib/Integrations/Bartec.pm
- t/open311/endpoint/bartec.t
- t/open311/endpoint/xml/bartec/extended_definitions.xml
Not all Bartec values follow the pattern the regex was looking for. As a result the `$1` might have been empty causing a schema validation error when trying to fetch the service metadata.
Additionally, on macOS the `$1` value was sometimes `darwin`, oddly, which meant that all values had that as their label if the regex didn’t match.
> [Bartec] Handle extended data values without ‘ - ’ correctly

- perllib/Integrations/Symology.pm
- perllib/Open311/Endpoint/Integration/Symology.pm
- t/open311/endpoint/brent.t
- t/open311/endpoint/brent_symology.yml
This will let someone specify e.g. a default fallback Priority.
Could simplify the existing Central Beds config as well with this.
> [Symology] Add request default config.

- conf/council-bromley_echo.yml-example
- perllib/Integrations/Echo.pm
- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/echo.t
- t/open311/endpoint/echo.yml
This lets us specify which Echo servers are waste and which aren't (for group/type), lets us have category grouping (wasn't needed for Waste), and lets us report without a UPRN (I’ve used USRN for Bromley, docs imply it should work only with lat/long but it did not for me).
> [Echo] Initial changes for FMS reporting

- conf/council-www.bromley.gov.uk.yml-example
- perllib/Open311/Endpoint/Integration/Multi.pm
- perllib/Open311/Endpoint/Integration/Passthrough.pm
- perllib/Open311/Endpoint/Integration/UK/Bromley.pm
- perllib/Open311/Endpoint/Integration/UK/Bromley/Echo.pm
- perllib/Open311/Endpoint/Integration/UK/Bromley/Passthrough.pm
- perllib/Open311/Endpoint/Role/ConfigFile.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- t/open311/endpoint/bromley.t
- t/open311/endpoint/bromley_echo.t
- t/open311/endpoint/passthrough.t
- t/open311/endpoint/uk.t
This will pass the data it receives through to an external Open311 endpoint, and pass what it receives back (validating as it does).
Along with this, move Bromley to a Multi backend with Echo and Passthrough children.
This is so we can move from FMS only talking directly to Bromley's system to going via open311-adapter, without having to have a bunch of devolved contacts at the FMS end. `ignore_services` is so we can ignore the Bromley services that are moving to Echo (I'm sure they'll remove them for testing soon anyway, but thought might as well have this for now).
Needs POD documentation.
> Add Passthrough integration

- perllib/Integrations/Symology.pm
- perllib/Open311/Endpoint/Integration/UK/Camden.pm
- t/open311/endpoint/camden.t
This field has been configured to accept FixMyStreet photo URLs and display them in the Symology interface.
This is largely based on the work @davea did in https://github.com/mysociety/open311-adapter/pull/190.
Fixes https://github.com/mysociety/societyworks/issues/3492
> [Camden] Send photo URLs to field in Symology

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/UK/Oxfordshire/AlloyV2.pm
- t/open311/endpoint/alloyv2.t
Issue with Oxfordshire having jobs within Alloy updating FMS statuses when the job has a parent defect.
They only want the status on FMS to be updated when the parent status is updated, which is what they want to be reflected to the citizen.
This adds finer control over which type of jobs with parent defects should be skipped over by respective councils.
Maintains the status quo for all except Oxford.
https://mysocietysupport.freshdesk.com/a/tickets/2668
> [Oxfordshire][Open311] Finer control for jobs with parent defects updating FMS

- bin/symology/fetch_files
When moving the files retrieved from SFTP to their destination tell `mv` to skip any files that already exist.
This should fix the cleanup script, which currently isn't removing files because they're getting updated every time they're pulled.
> [Symology] Don't overwrite existing files retrieved from SFTP

- bin/symology/cleanup_remote_files
Looks for XML files that are older than one week on Symology's SFTP server and removes them.
It gets the files timestamp from the filename, rather than relying on the creation time of the remote file.
Fixes https://github.com/mysociety/societyworks/issues/3452
Fixes https://github.com/mysociety/societyworks/issues/3473
> [Symology] Script to cleanup remote XML files

- perllib/Open311/Endpoint/Integration/Echo.pm
- perllib/Open311/Endpoint/Integration/UK/Brent/Echo.pm
- t/open311/endpoint/brent.t
- t/open311/endpoint/brent_echo.yml
Missed collections must check mandatory fields. Currently we can't see how to differentiate between bins and bags so check both fields for any missed collection although only one field is mandatory.
Relates to Brent WW go-live: Missed collection events https://3.basecamp.com/4020879/buckets/28996137/todolists/5888021261
> [Echo][Brent] Adds extra mandatory fields for missed collection

- conf/council-lincolnshire_confirm.yml-example
- perllib/Integrations/Confirm.pm
- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- perllib/Open311/Endpoint/Service/Request/Alloy.pm
- perllib/Open311/Endpoint/Service/Request/Confirm.pm
- perllib/Open311/Endpoint/Service/Role/CanBeNonPublic.pm
- t/open311/endpoint/confirm.yml
- t/open311/endpoint/lincolnshire.t
Lincolnshire want reports created in Confirm to be associated with the correct user so that the user can receive updates from FixMyStreet.
This change get the customer name and email from Confirm and passes them to FMS in the GET Service Requests call.
FixMyStreet change that uses this data: https://github.com/mysociety/fixmystreet/pull/4110
Part of https://github.com/mysociety/societyworks/issues/3079
> [Lincolnshire] Pass customer details through from Confirm

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- t/open311/endpoint/json/alloyv2/northumberland_defects_query_response.json
If this goes live, we'll have to update the update cron to call the Alloy endpoints less often (assuming they'll now be taking longer than the update frequency).
> [Alloy] Sleep between reconstruct calls

- perllib/Integrations/Bartec.pm
- perllib/Integrations/Confirm.pm
- perllib/Open311/Endpoint/Integration/Bartec.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Integration/Echo.pm
- perllib/Open311/Endpoint/Integration/Ezytreev.pm
- perllib/Open311/Endpoint/Integration/SalesForce/EastSussex.pm
- perllib/Open311/Endpoint/Integration/SalesForce/Rutland.pm
- perllib/Open311/Endpoint/Integration/Symology.pm
- perllib/Open311/Endpoint/Integration/Uniform.pm
- perllib/Open311/Endpoint/Integration/WDM.pm
- perllib/Open311/Endpoint/Role/ConfigFile.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- perllib/Role/EndpointConfig.pm
- perllib/Role/Logger.pm
Fixes https://github.com/mysociety/societyworks/issues/3658. This should cover anything using Role::Logger and SOAP::Lite.
Role::Logger now passes in its config filename (if present) to the Open311::Endpoint::Logger to be used to look up the log file location (rather than always falling back to general.yml). The changes to O::E::Role::ConfigFile and Role::EndpointConfig are only so that config_filename is set for more things (that otherwise skipped straight to setting `config_file`).
SOAP::Lite only has the one hook for debug logging, so I set a log identifier in the Endpoint package before each call to the SOAP API, to log to the appropriate place. Bit ugly, but seems to work in staging.
> Log different integrations to different files.

- perllib/Integrations/Echo.pm
- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/brent.t
What ID to use in PerformEventAction depends upon the state the event is currently in in Echo. The state coming from FMS may be a state change. This should fix the occasional stuck Brent update due to the wrong IDs being used.
Fixes https://github.com/mysociety/societyworks/issues/3683
> [Brent] Check existing state in Echo for update.

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- t/open311/endpoint/alloyv2.t
Tested locally in addition to test case. Working as expected.
> [Alloy] Handle failed attachment downloads.

- perllib/Integrations/Abavus.pm
- perllib/Open311/Endpoint/Integration/Abavus.pm
- t/open311/endpoint/abavus.t
- t/open311/endpoint/abavus.yml
Checks against the 'result' rather than the 'id' - there should be one result for creating a serviceRequest and 0 for failure. Seems more solid than the 'id' returning -1 which I couldn't see documented.
Also changes fields read to correct Abavus return field names.
Adds in a photo field to send the urls of photos on the report.
Also adds a test for the photo field and a check that all fields are being tested as currently there could be a silent failure if checking fields breaks down.
> Abavus update read fields and add photos field

- perllib/Open311/Endpoint/Integration/Abavus.pm
- t/open311/endpoint/abavus.t
When creating a report it needs to have a systemCode and a reference added - systemCode is hardcoded to 'FMS' to match the Bucks profile.
reference is the FMS id as the external id.
This is for the forthcoming 'event' call that will allow fetching updated reports and will need these present to work at the Abavus end.
https://3.basecamp.com/4020879/buckets/32325686/todos/6191167800#__recording_6245727608
> [Bucks][Abavus] Add adding of reference and systemCode

- perllib/Open311/Endpoint/Integration/Multi.pm
- t/open311/endpoint/multi.t
If one backend of a Multi endpoint fails, and we skip it, only the non-erroring results will be returned, leading to the erroring services being removed from the front end.
Fixes https://github.com/mysociety/open311-adapter/issues/275
> [Multi] Error if any failure in a services call.

- bin/centralbedfordshire/jadu/init_update_gathering_files
Small thing I bumped in to when go-living.
> [open311-adapter] [Central Beds] Allow zero lookback-days when initialising Jadu state gathering files.

- perllib/Open311/Endpoint/Integration/Confirm.pm
- t/open311/endpoint/gloucestershire.t
For the to-dos in https://3.basecamp.com/4020879/buckets/32187059/todolists/5997794619.
> Glos confirm integration post testing fixes

- perllib/Open311/Endpoint/Integration/ATAK.pm
- t/open311/endpoint/brent.t
This was using the FixMyStreet external ID as the service_request_id, which meant it wasn't getting matched when the updates were pulled into FMS.
Use the ATAK ID rather than the FMS reference as the service_request_id.
Follows on from #294
> [ATAK] Use the ATAK ID for service_request_id

- perllib/Integrations/Echo.pm
- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/sutton.t
For e.g. bulky collections the same GUID used by FMS in the `ReserveAvailableSlotsForEvent` call must be used for subsequent `PostEvent` call.
For https://github.com/mysociety/societyworks/issues/3758
> [Echo] Allow PostEvent GUID to be set by Open311

- conf/council-brent_atak.yml-example
- perllib/Open311/Endpoint/Integration/ATAK.pm
- perllib/Open311/Endpoint/Service/UKCouncil/ATAK.pm
- t/open311/endpoint/brent.t
https://github.com/mysociety/societyworks/issues/3898
Construct the description open311-adapter side using title, URL and detail values from FMS. Truncate the detail to ensure the whole issue text is less than some config defined character limit.
> [ATAK] Enforce character limit on issue text.

- perllib/Open311/Endpoint/Integration/ATAK.pm
- perllib/Open311/Endpoint/Service/UKCouncil/ATAK.pm
- t/open311/endpoint/brent.t
Add group to the issue text when creating an issue in ATAK.
See also https://github.com/mysociety/fixmystreet/pull/4600, which populates the group attribute on the FMS side.
Fixes https://github.com/mysociety/societyworks/issues/3836
> [ATAK] Add group to issue text

- perllib/Integrations/Bartec.pm
- t/open311/endpoint/bartec.t
Add encoding to email addresses in case of special characters in email addresses prompted by an email with an ampersand in it
> [Bartec] Encode email in case of special characters

- bin/symology/fetch_files
The trap to remove the TMPDIR being set-up within the loop doesn't work as expected as it gets updated with each iteration and leaves directories behind.
This sets up a top-level TMPDIR and sets a single global trap to clean that up on exit.
> [Symology] Use a top-level TMPDIR when fetching files

- conf/council-brent_atak.yml-example
- perllib/Open311/Endpoint/Integration/ATAK.pm
- t/open311/endpoint/brent.t
- If `task_comments` is present but blank default to "fixed".
- If `task_comments` is present, not blank, but not a know status default to "closed".
Fixes https://github.com/mysociety/societyworks/issues/3926
> [Brent] [ATAK] Change FMS status mappings

- conf/council-brent_atak.yml-example
- perllib/Open311/Endpoint/Integration/ATAK.pm
- t/open311/endpoint/brent.t
We were already setting the FMS status code correctly, but were missing the external status code for reports that were automatically marked as closed, which was causing some warnings.
> [Brent][ATAK] Set external status code for closed reports

- perllib/Open311/Endpoint/Integration/Symology.pm
- t/open311/endpoint/bexley_symology.t
- t/open311/endpoint/brent.t
The category configuration is only needed if the category has a specific ServiceCode. So if no category has a specific ServiceCode, we can assume we can pass through updates regardless of if the category matches one or not. This lets us send through updates on now-deleted category reports.
> [Symology] Update when only default ServiceCode.

- conf/council-bexley_whitespace.yml-example
This documents the format that is expected of the service_mapping config key.
Follows on from https://github.com/mysociety/open311-adapter/pull/337 (because I accidentally merged that one without reading the comments!)
> [Bexley][Whitespace] Add example service_mapping config

- perllib/Open311/Endpoint/Integration/UK/Bexley/Whitespace.pm
- perllib/Open311/Endpoint/Integration/Whitespace.pm
- t/open311/endpoint/bexley.t
Instead of passing through the FMS description Bexley want to have details about whether a property is assisted and the location of the containers in the message that goes to Whitespace.
For https://3.basecamp.com/4020879/buckets/35109031/todos/7265317231
Part of https://github.com/mysociety/societyworks/issues/4206
> [Bexley][Whitespace] Use custom message for worksheet

- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/echo.t
- t/open311/endpoint/echo.yml
If we have used a suffix in the categories of FMS to allow us to use one Event Type with separate category names, we strip the suffix before sending to Echo so the report is sent to the base Event type
https://github.com/mysociety/societyworks/issues/4365
> [Echo] Strip suffixes defined by _

- conf/council-merton_echo.yml-example
- conf/council-www.merton.gov.uk.yml-example
- perllib/Open311/Endpoint.pm
- perllib/Open311/Endpoint/Integration/Multi.pm
- perllib/Open311/Endpoint/Integration/Passthrough.pm
- perllib/Open311/Endpoint/Integration/UK.pm
- perllib/Open311/Endpoint/Integration/UK/Merton.pm
- perllib/Open311/Endpoint/Integration/UK/Merton/Echo.pm
- perllib/Open311/Endpoint/Integration/UK/Merton/Passthrough.pm
- t/open311/endpoint/merton.t
- t/open311/endpoint/merton.yml
- t/open311/endpoint/merton_echo.t
- t/open311/endpoint/uk.t
- t/open311/endpoint/xml/merton/requestpost.xml
- t/open311/endpoint/xml/merton/service.xml
- t/open311/endpoint/xml/merton/services.xml
- t/open311/endpoint/xml/merton/token.xml
For https://github.com/mysociety/societyworks/issues/4238
> [Merton] Initial setup.

- perllib/Open311/Endpoint/Integration/Whitespace.pm
This prevents errors when Whitespace is used as part of a multi integration.
> [Whitespace] Add blank get_service_request_updates

- perllib/Open311/Endpoint/Integration/Boomi.pm
- t/open311/endpoint/surrey_boomi.t
Surrey will be sending an externalId specifically to be used for imported jobs and reports
https://3.basecamp.com/4020879/buckets/36546415/todos/7672617616#__recording_7683887161 https://mysociety.slack.com/archives/C06SKSH5KQT/p1722948392215939
> [Surrey] Adds externalId for jobs and reports

- perllib/Open311/Endpoint/Integration/Boomi.pm
- t/open311/endpoint/surrey_boomi.t
Photos should only be uploaded if the photo content was POSTed from FMS.
> [Surrey] Don’t fetch & upload photos from media_url

- perllib/Open311/Endpoint/Integration/Confirm.pm
Fetched Enquiries will be skipped if their status
maps to IGNORE in reverse_status_mapping.
Matches behaviour of update fetching in 42f75f6b.
> [Confirm] Allow ignoring of enquiries in certain status

- perllib/Integrations/Symology.pm
- perllib/Open311/Endpoint/Integration/Symology.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/Symology.pm
- perllib/Open311/Endpoint/Integration/UK/Brent/Symology.pm
- perllib/Open311/Endpoint/Integration/UK/Camden/Symology.pm
- perllib/Open311/Endpoint/Integration/UK/CentralBedfordshire/Symology.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Symology/Bexley.pm
- t/open311/endpoint/brent_symology.yml
- t/open311/endpoint/camden_symology.yml
- t/open311/endpoint/centralbedfordshire_symology.t
Move the adding of photos/URL to config lines, so easier to then add Bexley in FD-4648.
> [Symology] line refactor

- perllib/Open311/Endpoint/Integration/Echo.pm
- perllib/Open311/Endpoint/Integration/UK/Merton/Echo.pm
- perllib/Open311/Endpoint/Role/SLWP.pm
- t/open311/endpoint/merton_echo.t
Improve passing of payment details from FMS to here, to allow multiple payments.
To deal with issue outlined at https://3.basecamp.com/4020879/buckets/36310026/todos/7575957224#__recording_7650094140
> [Merton] Payment passthrough

- bin/alloy/inspect-designs
- bin/alloy/invoke
Adds a couple of command line tools for inspecting designs in an Alloy instance, and interacting with the Alloy API via the methods in the AlloyV2 module.
- `bin/alloy/inspect-designs` - Lets you view one or all designs in a given Alloy instance and shows attributes, their types and whether they're required in a text format.
- `bin/alloy/invoke` - Allows you to call methods in the AlloyV2 module from the command line and pass parameters in via JSON. Inspired by the `bin/fixmystreet.com/call-wasteworks-backend` tool in FMS.
> [Alloy] Add CLI tools for inspecting and interacting with the Alloy API

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/UK/NorthumberlandAlloy.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- t/open311/endpoint/json/alloyv2/northumberland/customer_requests_query_response.json
- t/open311/endpoint/northumberland_alloy.t
- t/open311/endpoint/northumberland_alloy.yml
For https://mysocietysupport.freshdesk.com/a/tickets/3082 / https://github.com/mysociety/societyworks/issues/4507.
Config changes for staging and live also made in mysociety-servers/vhosts/open311-adapter/conf_council-northumberland_alloy.yml.ugly.
> [Northumberland] Fetch extra_details from Alloy

- perllib/Integrations/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/UK/NorthumberlandAlloy.pm
- t/open311/endpoint/json/alloyv2/northumberland/customer_requests_query_response.json
- t/open311/endpoint/northumberland_alloy.t
- t/open311/endpoint/northumberland_alloy.yml
Fixes https://github.com/mysociety/societyworks/issues/4648.
> [N/land] Pass category updates to/from Alloy

- perllib/Open311/Endpoint/Integration/UK/Bristol/Passthrough.pm
- t/open311/endpoint/bristol_passthrough.t
The endpoint does not like it being present.
> [Bristol] No service_code on passthrough updates.

- perllib/Integrations/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- t/integrations/alloyv2.t
- t/integrations/alloyv2.yml
- t/integrations/json/alloyv2/join_response.json
- t/open311/endpoint/alloyv2.t
- t/open311/endpoint/alloyv2.yml
- t/open311/endpoint/json/alloyv2/defect_search.json
Rather than separate per-item parent calls which are hitting the rate limit.
https://github.com/mysociety/societyworks/issues/4682.
On staging. Configuration commit on servers is `7c0c1a46f59d0bec7641e42279f4675a88c39448`. Live configuration will just be case of removing the staging guards - the values should be the same.
> [Alloy] Allow using a join to check if defects are linked.

- perllib/Integrations/WDM.pm
- t/open311/endpoint/oxfordshire_wdm.t
- t/open311/endpoint/oxfordshire_wdm.yml
We have added some extra fields for a raised inspection and this processes the fields sent from FMS to transfer to WDM.
Changes needed to the configuration to add uids and change the format for the previous defect_mapping.
https://github.com/mysociety/societyworks/issues/4854
> [Oxfordshire][Open311] Extra fields for raised inspection

- perllib/Open311/Endpoint/Integration/Agile.pm
- t/open311/endpoint/agile.t
There was a typo in the value for credit cards and CSC, it's now CREDITDCARD, with the D, which matches the [API docs](https://docs.google.com/document/d/1gPBFFXGMXEun8qTxGkjL2vc0dAKw09Ft/edit).
Added some tests for the payment method, which feels quite verbose compared to the code change, but think it covers all cases.
For [this Basecamp discussion](https://3.basecamp.com/4020879/buckets/40373795/todos/8407498579#__recording_8489124569)
> [Bexley][WW] Fix value for credit card payments send to Agile

- conf/council-www.banes.gov.uk.yml-example
- perllib/Open311/Endpoint.pm
- perllib/Open311/Endpoint/Integration/Passthrough.pm
- perllib/Open311/Endpoint/Integration/UK.pm
- perllib/Open311/Endpoint/Integration/UK/BANES.pm
- perllib/Open311/Endpoint/Integration/UK/BANES/Confirm.pm
- perllib/Open311/Endpoint/Integration/UK/BANES/Passthrough.pm
- perllib/Open311/Endpoint/Service/Attribute.pm
- t/open311/endpoint/banes_passthrough.t
- t/open311/endpoint/uk.t
- t/open311/endpoint/www.banes.gov.uk.yml
Makes BANES  a multi.
Passthrough will receive all reports with an email address in them and any others will go to Confirm.
https://github.com/mysociety/societyworks/issues/4746
> [BANES][Open311] Create a multi with a Passthrough

- perllib/Open311/Endpoint/Integration/UK/Gloucester.pm
Alloy requires both of these codes, but does not give very helpful error message if they are missing. So have added a check our end.
> [Glos City] Die if parent category or service area codes are not found

- perllib/FixMyStreet/WorkingDays.pm
- perllib/Open311/Endpoint/Integration/UK/Gloucester.pm
- t/open311/endpoint/gloucester_alloy.t
- t/open311/endpoint/gloucester_alloy.yml
Bit of duplication of FMS working day code, but seemed easier to hold it all within open311-adapter.
Server config would be as in tests, but for all the categories that needed to be High and with all the target SLAs.
Fixes https://github.com/mysociety/societyworks/issues/5018
> [Gloucester] Send through priority and target date 

- perllib/Open311/Endpoint/Integration/UK/Gloucester.pm
- t/open311/endpoint/gloucester_alloy.t
For https://3.basecamp.com/4020879/buckets/38208405/todos/8821272844
Providing a full datetime rather than only a date (that is defaulting to midnight UTC at start of day).
> [Gloucester] Set target date to end of day.

- perllib/Integrations/Confirm.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
For https://github.com/mysociety/societyworks/issues/5055
For https://github.com/mysociety/societyworks/issues/5042
Didn't seem worth adding a test, because all that would be changing is the mocked returned data, so have to test it works outside anyway (this appears to be the correct formulation hopefully, used for enquiries commit for the number, and network panel of UI for the target date boolean).
> [Aberdeenshire] Ignore defects linked to our own enquiries; only fetch defects with target date.
