- conf/general.yml-example
- perllib/Integrations/SalesForce.pm
- perllib/Integrations/SalesForce/Rutland.pm
- perllib/Open311/Endpoint.pm
- perllib/Open311/Endpoint/Integration/SalesForce.pm
- perllib/Open311/Endpoint/Integration/UK.pm
- perllib/Open311/Endpoint/Integration/UK/Rutland.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- perllib/Open311/Endpoint/Schema.pm
- perllib/Open311/Endpoint/Service/Attribute.pm
- perllib/Open311/Endpoint/Service/Request.pm
- perllib/Open311/Endpoint/Service/Request/SalesForce.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Rutland.pm
- t/open311/endpoint/rutland.t
This adds an integration for pushing and pulling from Rutland's Salesforce API.
> Rutland salesforce

- perllib/Integrations/Confirm.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Integration/UK/EastHerts.pm
- perllib/Open311/Endpoint/Service/Request/ExtendedStatus.pm
- perllib/Open311/Endpoint/Service/Request/SalesForce.pm
- perllib/Open311/Endpoint/Service/Role/ExtendedStatus.pm
Pulled out from now-merged #6.
> Implement get_service_requests to return Enquiries from Confirm

- .travis.yml
- conf/council-banes_confirm.yml-example
- perllib/Integrations/Confirm/BANES.pm
- perllib/Open311/Endpoint/Integration/UK/BANES.pm
This PR adds all of the BANES-specific code for their integration. I have left the commits mostly as they occurred so you can see the history of how things progressed and perhaps the rationale behind the structure.
> BANES Confirm integration

- .travis.yml
- conf/council-buckinghamshire_confirm.yml-example
- perllib/Integrations/Confirm/Buckinghamshire.pm
- perllib/Open311/Endpoint/Integration/UK/Buckinghamshire.pm
This PR contains all of the Buckinghamshire-specific code to support their Confirm integration. As with the others I have left commits as they occurred, though it's obvious that most of the hard thinking and mistakes had been made during the BANES branch and as such this is a bit smaller :)
> Buckinghamshire Confirm integration

- perllib/Integrations/Confirm.pm
- t/open311/endpoint/confirm.t
Stops those annoying "Logged Date 04/06/2018 15:33:28 must be greater than the Effective Date of current status log" errors.
> [Confirm] Retry EnquiryUpdate if rejected for too early LoggedTime

- perllib/Integrations/WDM.pm
- perllib/Integrations/WDM/Oxfordshire.pm
- perllib/Open311/Endpoint/Integration/UK.pm
- perllib/Open311/Endpoint/Integration/UK/Oxfordshire.pm
- perllib/Open311/Endpoint/Integration/WDM.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- perllib/Open311/Endpoint/Service/Request/Update/mySociety.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Oxfordshire.pm
- t/open311/endpoint/oxfordshire.t
- t/open311/endpoint/oxfordshire.yml
Adds integration with WDM for OCC.
Only handles new reports, new updates and fetching updates. OCC categories are configured on FMS for the time being.
> Oxfordshire WDM integration

- perllib/Open311/Endpoint/Role/mySociety.pm
- perllib/Open311/Endpoint/Service/Request/Update/mySociety.pm
Connects https://github.com/mysociety/fixmystreet-freshdesk/issues/22#issuecomment-427369740
> Add reopen status.

- perllib/Open311/Endpoint/Integration/Alloy.pm
if the search returns more than one page fetch all the pages and merge
them into one
> [Alloy] page through search results

- conf/council-bexley.yml-example
- cpanfile
- cpanfile.snapshot
- perllib/Open311/Endpoint/Integration/Symology.pm
- perllib/Open311/Endpoint/Service/Request/Update.pm
- t/open311/endpoint/bexley.t
Fetches CSV file of updates, filters to within the requested date range, and outputs matches as Open311 updates for FMS to consume.
> [Bexley] Initial update fetching code.

- perllib/Integrations/Confirm.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm_private_services.yml
> [Confirm] Private services, new code

- perllib/Integrations/Symology.pm
- perllib/Open311/Endpoint/Integration/Symology.pm
- t/open311/endpoint/bexley.t
We were passing them all as CCA, but they have asked for ones that fix/close the issue to use CR instead.
> [Bexley] Pass closing update through with CR code.

- perllib/Open311/Endpoint/Integration/Alloy.pm
- t/open311/endpoint/alloy.t
- t/open311/endpoint/json/alloy/defect_search_all.json
- t/open311/endpoint/json/alloy/defect_search_multiple.json
- t/open311/endpoint/json/alloy/inspect_search.json
Use the version startDate for update times which is the correct thing to do according to Yotta.
> [Alloy] use startDate for updatetime

- perllib/Integrations/Alloy.pm
- perllib/Open311/Endpoint/Integration/Alloy.pm
- perllib/Open311/Endpoint/Integration/UK/Northamptonshire.pm
- t/open311/endpoint/alloy.t
- t/open311/endpoint/alloy.yml
This enables sending updates to Alloy by appending them to a customer comments field.
> Send updates to Alloy

- .travis.yml
- perllib/Integrations/SalesForce/Rutland.pm
- perllib/Open311/Endpoint/Integration/Alloy.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Role/ConfigFile.pm
- perllib/Role/Config.pm
- t/open311/endpoint.t
- t/open311/endpoint/alloy.t
- t/open311/endpoint/bexley.t
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm_upload.t
- t/open311/endpoint/mysociety.t
- t/open311/endpoint/oxfordshire.t
- t/open311/endpoint/rutland.t
- t/open311/endpoint/warwick.t
- t/open311/endpoint/warwick_dbd.t
I didn't want to have to add yet more lines to Travis and forget to do it locally :)
Also fixes to run on newer perl without needing an envvar.
> Test fixes

- README.md
Basic README with some details on how to get the application installed and what to do with it once it's installed.
Fixes https://github.com/mysociety/open311-adapter/issues/56
> Add README.md with install and usage instructions

- conf/council-island_roads_confirm.yml-example
- perllib/Integrations/Confirm.pm
- perllib/Integrations/Confirm/IslandRoads.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Integration/UK/IslandRoads.pm
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm_omit_logged.yml
Confirm integration for Island Roads.
> Island roads confirm

- notes/ncc_alloy.md
- perllib/Open311/Endpoint/Integration/Alloy.pm
- t/open311/endpoint/json/alloy/inspect_search.json
- t/open311/endpoint/json/alloy/resource_3027030_v271881.json
Avoids spurious updates.
Also a doc with some notes on how alloy works.
> [Alloy] Only set external status code if relevant 

- t/open311/endpoint/confirm.t
We don't want to leak the StatusLogNotes that we send to Confirm in the open311-adapter output.
This came up when discussing https://github.com/mysociety/fixmystreet-commercial/issues/1574 with @dracos.
> [Confirm] Test that StatusLogNotes doesn't appear in updates

- conf/council-bexley_uniform.yml-example
- cpanfile
- cpanfile.snapshot
- perllib/Integrations/Uniform.pm
- perllib/Open311/Endpoint/Integration/UK.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/Uniform.pm
- perllib/Open311/Endpoint/Integration/Uniform.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Uniform.pm
- t/open311/endpoint/bexley.t
- t/open311/endpoint/bexley_uniform.t
- t/open311/endpoint/uk.t
- t/open311/endpoint/uniform.t
Sending reports, sending updates, fetching updates.
> [Bexley] Initial Uniform setup.

- perllib/Integrations/Ezytreev.pm
- perllib/Open311/Endpoint/Integration/Ezytreev.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Ezytreev.pm
- t/open311/endpoint/ezytreev.t
Integration with the new ezytreev API, which will initially be implemented for Peterborough.
Note that because this is being done for Peterborough there may be some Peterborough-specific assumptions that have unintentionally snuck in here.
The Peterborough-specific bits will be added in a separate PR (currently a WIP: https://github.com/mysociety/open311-adapter/pull/83).
> [Ezytreev] Add integration

- perllib/Open311/Endpoint/Integration/Alloy.pm
- perllib/Open311/Endpoint/Integration/UK/Northamptonshire.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- perllib/Open311/Endpoint/Service/Request/Update/mySociety.pm
- t/open311/endpoint/alloy.t
- t/open311/endpoint/json/alloy/defect_search_multiple.json
- t/open311/endpoint/northamptonshire_alloy.t
Generate a description for defects that includes the priority and the type when fetching new defects from Northamptonshire Alloy.
For https://github.com/mysociety/fixmystreet-commercial/issues/1729
> Alloy get defect priority

- perllib/Open311/Endpoint/Integration/Uniform.pm
- t/open311/endpoint/bexley_uniform.t
- t/open311/endpoint/uniform.t
> [Uniform] Skip unneeded requests fetching updates.

- perllib/Integrations/SalesForceRest.pm
- perllib/Open311/Endpoint/Integration/SalesForceRest.pm
- t/open311/endpoint/case_1.json
- t/open311/endpoint/eastsussex.t
Fetch the case id from salesforce as the request id and not the salesforce id as the former is more meaningful to the customer
> East sussex salesforce caseid

- perllib/Open311/Endpoint/Integration/SalesForceRest.pm
We not only need to check that a service has a group in the whitelist,
we also need to remove any groups that aren't in it.
> [EastSussex] remove non whitelisted groups from service

- perllib/Integrations/SalesForceRest.pm
- perllib/Open311/Endpoint/Integration/SalesForceRest.pm
- t/open311/endpoint/eastsussex.t
- t/open311/endpoint/eastsussex.yml
Add the contact id to the case as this is required by east sussex
> [EastSussex] update case with contact id

- perllib/Open311/Endpoint/Service/UKCouncil/Salesforce.pm
- t/open311/endpoint/eastsussex.t
Otherwise the front end does not save them.
> [EastSussex] hidden fields should be set to variable

- perllib/Open311/Endpoint.pm
- perllib/Open311/Endpoint/Integration/SalesForceRest.pm
- perllib/Open311/Endpoint/Service/Attribute.pm
- t/open311/endpoint.t
- t/open311/endpoint/Endpoint1.pm
- t/open311/endpoint/eastsussex.t
- t/open311/endpoint/eastsussex.yml
Allow values in singlevalue list answers to have a specified sort order.
> East sussex sort order

- perllib/Open311/Endpoint/Service/UKCouncil/Alloy.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Confirm.pm
- t/open311/endpoint/alloy.t
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm_attributes.t
- t/open311/endpoint/confirm_wrapped.t
- t/open311/endpoint/ezytreev.t
In case they are displayed as text inputs anywhere potentially.
> Switch a few attributes from text to string.

- perllib/Integrations/Confirm.pm
- perllib/Open311/Endpoint/Integration/UK.pm
- t/open311/endpoint/confirm_upload.t
For https://github.com/mysociety/fixmystreet-commercial/issues/1778
> [Confirm] Improve photo uploading error handling & fix multi integration bug

- conf/council-bromley_echo.yml-example
- cpanfile
- cpanfile.snapshot
- perllib/Integrations/Confirm.pm
- perllib/Integrations/Echo.pm
- perllib/Open311/Endpoint.pm
- perllib/Open311/Endpoint/Integration/Echo.pm
- perllib/Open311/Endpoint/Integration/UK.pm
- perllib/Open311/Endpoint/Integration/UK/Bromley.pm
- perllib/Open311/Endpoint/Service.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Echo.pm
- t/open311/endpoint.t
- t/open311/endpoint/Endpoint1.pm
- t/open311/endpoint/bromley.t
- t/open311/endpoint/confirm_upload.t
- t/open311/endpoint/echo.t
- t/open311/endpoint/echo.yml
- t/open311/endpoint/uk.t
For https://github.com/mysociety/fixmystreet-commercial/issues/1897
This should handle the posting of reports fully, there is example config but can also see the one in use on staging on mastodon in /data/servers.
> Echo support

- perllib/Integrations/Echo.pm
- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/echo.t
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1922
> [Echo] Post update

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/UK/Hackney.pm
- t/open311/endpoint/alloyv2.t
A couple of bug fixes and some customisation for the way Hackney defects are configured in Alloy.
> [Hackney] Small changes to support defect fetching

- perllib/Open311/Endpoint/Integration/Alloy.pm
- perllib/Open311/Endpoint/Integration/UK/Northamptonshire.pm
- t/open311/endpoint/alloy.yml
- t/open311/endpoint/json/alloy/ncc_inspect_search.json
- t/open311/endpoint/json/alloy/ncc_resource_3027029_v272125.json
- t/open311/endpoint/northamptonshire_alloy.t
Adds the user's name and any contact details in to the update message
Fixes https://github.com/mysociety/fixmystreet-freshdesk/issues/113
> [Northamptonshire] add user's details to updates

- perllib/Open311/Endpoint/Integration/Bartec.pm
- t/open311/endpoint/bartec.t
- t/open311/endpoint/bartec.yml
- t/open311/endpoint/xml/bartec/servicerequests_types_get.xml
Handle some edge cases in Bartec categories with
* non unique category names
* mapping service classes to categories
> Bartec category handling fixes

- perllib/Open311/Endpoint/Integration/Bartec.pm
- perllib/Open311/Endpoint/Integration/Multi.pm
- t/open311/endpoint/bartec.yml
- t/open311/endpoint/peterborough.t
Move statuses to config and whole thing to a function.
> [bartec] refactor skip request in request fetching

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- t/open311/endpoint/alloyv2.yml
- t/open311/endpoint/alloyv2_ncc.yml
- t/open311/endpoint/json/alloyv2/categories_search.json
no title now, instead it's in an attrbute
> [Alloy] change how we look up category id

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- t/open311/endpoint/alloyv2.t
> [AlloyV2] working updates with photos

- perllib/Integrations/WDM.pm
- t/open311/endpoint/oxfordshire.t
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1956
> [Oxfordshire] Don’t send USRN to WDM

- conf/council-centralbedfordshire_symology.yml-example
- perllib/Integrations/Symology.pm
- perllib/Open311/Endpoint/Integration/Symology.pm
- perllib/Open311/Endpoint/Integration/UK/CentralBedfordshire.pm
- t/open311/endpoint/bexley_symology.t
- t/open311/endpoint/uk.t
A couple of tweaks to get a basic integration up and running for sending reports in.
> [Central Beds] Initial Symology integration

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/UK/NorthamptonshireAlloyV2.pm
- t/open311/endpoint/alloyv2.t
- t/open311/endpoint/alloyv2_ncc.yml
- t/open311/endpoint/json/alloyv2/defect_search_all.json
- t/open311/endpoint/json/alloyv2/defect_search_all_ncc.json
- t/open311/endpoint/northamptonshire_alloyv2.t
See https://announcements.alloyapp.io/removal-of-item-title-subtitle-and-geometry-properties-(phase-2)-3Jrpcs
> [AlloyV2] Use new attribute instead of item for geometry

- perllib/Integrations/WDM.pm
- perllib/Open311/Endpoint/Integration/WDM.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- t/open311/endpoint/oxfordshire.t
- t/open311/endpoint/oxfordshire.yml
Part of https://github.com/mysociety/fixmystreet-commercial/issues/1847
> [Oxfordshire] HIAMS defect API integration

- cpanfile.snapshot
See https://github.com/toddr/YAML-Syck/issues/57
> Upgrade YAML::Syck for macOS Big Sur compatibility

- bin/centralbeds/fetch_symology_csv
Removes a gotcha when deploying on a new server for the first time.
> [Central Beds] Ensure SFTP SSH keys are accepted when fetching CSVs

- perllib/Integrations/SalesForce.pm
- perllib/Integrations/WDM.pm
- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/Bartec.pm
- perllib/Open311/Endpoint/Integration/Ezytreev.pm
Fixes https://github.com/mysociety/sysadmin/issues/1410
> Prevent a number of uninitialized warnings.

- perllib/Open311/Endpoint/Integration/UK/Bexley/Uniform.pm
- t/open311/endpoint/bexley_uniform.t
Fixes https://github.com/mysociety/fixmystreet-commercial/issues/1930
> [Bexley] Add new NAP status code to Uniform

- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/echo.t
For https://github.com/mysociety/fixmystreet/pull/3348
Also includes the parent change from another branch so it's hopefully easier to merge that in later.
> [Echo] Take first value found rather than last

- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/echo.t
- t/open311/endpoint/echo.yml
This is the catch all branch for the waste phase 2 changes.
> Bromley waste phase2 reviewed

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- t/open311/endpoint/alloyv2.t
Add support for upload_files in AlloyV2. This came up after putting Hackney Alloy highways live.
See https://github.com/mysociety/fixmystreet/pull/3590 for the related FixMyStreet fix.
> [AlloyV2] Support direct photo uploads as well as photo URLs

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- t/open311/endpoint/alloyv2.yml
- t/open311/endpoint/alloyv2_ncc.yml
- t/open311/endpoint/json/alloyv2/defect_search_all.json
- t/open311/endpoint/json/alloyv2/defect_search_all_ncc.json
The start field is now being set to 9999-12-31.
Fixes https://github.com/mysociety/societyworks/issues/2589
> [Alloy] Switch from start field to attribute.

- perllib/Integrations/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/UK/NorthamptonshireAlloyV2.pm
- t/open311/endpoint/alloyv2.t
- t/open311/endpoint/northamptonshire_alloyv2.t
These are all actually present on the live site at present, this tidies them up a bit.
> [Alloy] Some performance changes

- conf/council-hampshire_confirm.yml-example
- perllib/Open311/Endpoint/Integration/UK/Hampshire.pm
- t/open311/endpoint/uk.t
- Adds Endpoint file for Hampshire
- Adds test and example file to fulfil test
> [Hampshire] Adds open311 endpoint

- perllib/Integrations/Symology.pm
- perllib/Open311/Endpoint/Integration/Symology.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/Symology.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- t/open311/endpoint/bexley_symology.t
- t/open311/endpoint/centralbedfordshire.t
https://github.com/mysociety/societyworks/issues/3059
* Adds check for nsg_ref parameter and, if it exists, look up relevant code and add it to the Next Action
> [Bexley] Add next action to updates

- perllib/Integrations/SalesForce/Base.pm
- perllib/Integrations/SalesForce/EastSussex.pm
- perllib/Integrations/SalesForce/Rutland.pm
- perllib/Open311/Endpoint/Integration/SalesForce/EastSussex.pm
- perllib/Open311/Endpoint/Integration/SalesForce/Rutland.pm
- perllib/Open311/Endpoint/Integration/UK/EastSussex.pm
- perllib/Open311/Endpoint/Integration/UK/Rutland.pm
- t/open311/endpoint/eastsussex.t
- t/open311/endpoint/rutland.t
This means both options can use credentials or private keys.
For https://github.com/mysociety/societyworks/issues/1943
> [Salesforce] Factor common functions together.

- perllib/Open311/Endpoint/Integration/UK/Bromley.pm
- t/open311/endpoint/bromley.t
- t/open311/endpoint/echo.t
- t/open311/endpoint/echo.yml
The Echo event bits of https://github.com/mysociety/fixmystreet/pull/3745
> [Bromley] Add assisted collection event support.

- perllib/Open311/Endpoint.pm
- t/open311/endpoint/bartec.t
- t/open311/endpoint/xml/bartec/extended_definitions.xml
This will fix why `CREW NOTES` is not arriving at Bartec.
Fixes https://github.com/mysociety/societyworks/issues/3369
> Allow any characters in received attributes.

- perllib/Open311/Endpoint/Integration/UK/Bexley/Symology.pm
- t/open311/endpoint/bexley_symology.t
Firstly, tidies up the Symology code a bit to share more (hopefully helpful with upcoming XML work). Then adds spotting a new type of CSV file. Fixes https://github.com/mysociety/societyworks/issues/3264.
> [Bexley] New CSV parsing

- perllib/Open311/Endpoint/Integration/UK/Brent/Symology.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Symology/Brent.pm
- t/open311/endpoint/brent.t
FMS will be passing through the report title in an attribute so it can be mapped to the location for symology
https://github.com/mysociety/societyworks/issues/3407
> [Brent] Map title attribute to location

- perllib/Integrations/Echo.pm
- perllib/Open311/Endpoint/Integration/Echo.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Echo.pm
- t/open311/endpoint/bromley.t
- t/open311/endpoint/echo.t
- t/open311/endpoint/echo.yml
Plus couple of update bug fixes, missing required attribute, and documentation.
> [Echo] Extra attribute configuration

- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/echo.t
Fixes https://github.com/mysociety/societyworks/issues/3466
And couple of bug fixes in updates.
> [Echo] Add photo support

- perllib/Integrations/Bartec.pm
- perllib/Open311/Endpoint/Integration/Bartec.pm
- t/open311/endpoint/bartec.t
- t/open311/endpoint/bartec.yml
- t/open311/endpoint/xml/bartec/servicerequests_types_get.xml
For https://github.com/mysociety/societyworks/issues/3410.
Peterborough want bulky goods collection photos to be marked with the comment 'Bulky waste photo' (see https://3.basecamp.com/4020879/buckets/26662378/todos/5608057275).
> Set different comment on uploads if bulky collection

- perllib/Open311/Endpoint/Integration/UK/Kingston.pm
- perllib/Open311/Endpoint/Integration/UK/Sutton.pm
- t/open311/endpoint/sutton.t
- t/open311/endpoint/sutton.yml
Fixes https://3.basecamp.com/4020879/buckets/26876928/todos/5827020769
> [SLWP] Store DD payment type separately.

- perllib/Open311/Endpoint/Integration/UK/Camden.pm
- t/open311/endpoint/camden.t
Symology have added extra fields so that we can send up to three photos through along with the report.
Fixes https://github.com/mysociety/societyworks/issues/3492
> [Camden] Upload multiple photos to Symology

- perllib/Open311/Endpoint/Integration/UK/CentralBedfordshire.pm
- t/open311/endpoint/centralbedfordshire.t
For https://mysocietysupport.freshdesk.com/a/tickets/1076
> [Central Beds] Send photo URLs to field in Symology

- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/brent.t
- t/open311/endpoint/brent_echo.yml
For assisted collection name passthrough
> [Echo] Allow per-event type data_key_open311_map.

- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/bromley_echo.t
- t/open311/endpoint/echo.t
- t/open311/endpoint/echo.yml
Adding extra questions expanded from hidden fields and text fields to include dropdown lists
> [Open311] Adds creation of dropdown lists for extra questions from Echo

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/UK/NorthumberlandAlloy.pm
- t/open311/endpoint/northumberland_alloy.t
- t/open311/endpoint/northumberland_alloy.yml
fixes: https://github.com/mysociety/societyworks/issues/3669
> [Northumberland] [Alloy] Update Alloy status attribute on service request update.

- perllib/Open311/Endpoint/Integration/UK/Bromley/Passthrough.pm
- t/open311/endpoint/bromley.t
To deal with change made in https://github.com/mysociety/fixmystreet/pull/4440
> [Bromley] Back end does not handle a closed state.

- perllib/Open311/Endpoint/Integration/Abavus.pm
- t/open311/endpoint/abavus.t
- t/open311/endpoint/abavus.yml
- t/open311/endpoint/abavus_event.json
Adds fetching of updates from Abavus with new event/status call
Adds configuration for personNumber and catalogue code as this will be tested against demo.
Currently not tested against Abavus but created from details in https://3.basecamp.com/4020879/buckets/32325686/todos/6191167800#__recording_6254398386
> [Bucks][Abavus] Abavus fetch updates

- perllib/Open311/Endpoint/Integration/UK/Bexley/Symology.pm
- t/open311/endpoint/bexley_symology.t
> [Bexley] Update Symology status mapping

- perllib/Integrations/Echo.pm
- perllib/Open311/Endpoint/Integration/Echo.pm
- t/open311/endpoint/sutton.t
Similar to #298 but for the chosen reservation slot.
> [Echo] Allow PostEvent task reservation to be passed in.

- perllib/Open311/Endpoint/Integration/Echo.pm
- perllib/Open311/Endpoint/Integration/UK/Brent/Echo.pm
- t/open311/endpoint/echo.t
For https://github.com/mysociety/societyworks/issues/3900
> [Echo] Attach multiple images if received.

- perllib/Open311/Endpoint/Integration/UK/Bromley/Passthrough.pm
- t/open311/endpoint/bromley.t
This reverts commit 223f13ab1d440afbfa1077a52e7e749a52c68511.
Bromley are able to receive Closed status from latest message
https://mysocietysupport.freshdesk.com/a/tickets/3529
> Revert "[Bromley] Back end does not handle a closed state."

- perllib/Open311/Endpoint/Integration/UK/Bromley/Passthrough.pm
- t/open311/endpoint/bromley.t
https://mysocietysupport.freshdesk.com/a/tickets/3529
> [Bromley] Bromley have asked to have closed status functionality

- perllib/Open311/Endpoint/Integration/UK/Brent/Symology.pm
- t/open311/endpoint/brent.t
Sends photos from FMS to specified Symology fields
Request to send photos https://mysocietysupport.freshdesk.com/a/tickets/3548
Based on https://github.com/mysociety/open311-adapter/pull/255/files
> [Brent] Upload photos to Symology

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- perllib/Open311/Endpoint/Role/mySociety.pm
- t/open311/endpoint/alloyv2.t
And use this in the Alloy backend.
For https://github.com/mysociety/societyworks/issues/3709
> Allow updates to receive images as uploads.

- perllib/Open311/Endpoint/Role/SLWP.pm
- t/open311/endpoint/kingston.t
> [SLWP] No pound symbol in submitted data.

- bin/salesforce/old-get-credentials.pl
- bin/salesforce/refresh-token
- bin/symology/cleanup_files
- conf/council-rutland.yml-example
- perllib/Integrations/SalesForce/Base.pm
This moves the storage of the credentials to a file, and adds a script to update the token in that file.
Fixes https://github.com/mysociety/societyworks/issues/3726
> [Rutland] Add script to refresh token

- bin/whitespace/bexley-service-mapping
- conf/council-bexley_whitespace.yml-example
- perllib/Integrations/Whitespace.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/Whitespace.pm
- perllib/Open311/Endpoint/Integration/Whitespace.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Whitespace.pm
- t/open311/endpoint/bexley.t
- t/open311/endpoint/uk.t
- t/open311/endpoint/whitespace.t
- t/open311/endpoint/whitespace.yml
Adds a new Whitespace integration with support for reporting missed collections.
See also the FMS PR which makes the necessary changes on that side: https://github.com/mysociety/fixmystreet/pull/4890
Fixes https://github.com/mysociety/societyworks/issues/4051
Fixes https://github.com/mysociety/societyworks/issues/4098
> [Bexley] Whitespace missed collections

- perllib/Open311/Endpoint/Integration/UK/Bromley/Echo.pm
- t/open311/endpoint/bromley_echo.t
Notes text should not exceed maximum length for notes field.
https://github.com/mysociety/societyworks/issues/4232
https://3.basecamp.com/4020879/buckets/30553621/todos/7187142360#__recording_7288097933
> [Bromley][WW] Truncate text to maximum field length

- perllib/Open311/Endpoint/Integration/UK/Bexley/Symology.pm
https://mysocietysupport.freshdesk.com/a/tickets/4223
> [Bexley] Adds new action scheduled

- conf/council-brent_atak.yml-example
- perllib/Open311/Endpoint/Integration/ATAK.pm
- t/open311/endpoint/brent.t
fixes https://github.com/mysociety/societyworks/issues/3919
servers branch: `atak-byte-limit-not-char-limit`
> [ATAK] Enforce byte limit on issue text.

- perllib/Open311/Endpoint/Integration/Boomi.pm
- t/open311/endpoint/surrey_boomi.t
serviceId will be received from new version of Boomi integration so is not hard-coded
https://3.basecamp.com/4020879/buckets/36546415/todos/7648793252#__recording_7674131654 https://mysociety.slack.com/archives/C06SKSH5KQT/p1722624461300599?thread_ts=1722616474.424329&cid=C06SKSH5KQT
> [Surrey] Expect serviceId from integration

- perllib/Open311/Endpoint/Integration/Boomi.pm
- t/open311/endpoint/surrey_boomi.t
https://github.com/mysociety/societyworks/issues/4506
> [Surrey] Add description field

- perllib/Open311/Endpoint/Integration/Boomi.pm
- t/open311/endpoint/surrey_boomi.t
For https://github.com/mysociety/societyworks/issues/4540
> [Surrey] Remap invalid status from Boomi

- perllib/Open311/Endpoint/Integration/ATAK.pm
- t/open311/endpoint/brent.t
Fixes https://github.com/mysociety/societyworks/issues/4495.
Verified on staging with report [27945](https://staging.fixmystreet.com/admin/report_edit/27945).
> [ATAK] Handle uploaded photos.

- perllib/Integrations/Whitespace.pm
- perllib/Open311/Endpoint/Integration/Whitespace.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Whitespace.pm
- t/open311/endpoint/bexley.t
- t/open311/endpoint/whitespace.t
For https://github.com/mysociety/societyworks/issues/4575 & https://github.com/mysociety/societyworks/issues/4576.
Also have config changes in a `bexley-ww-container-requests` branch in mysociety-servers.
> [Bexley][WW] Create worksheets for container requests

- perllib/Integrations/Whitespace.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/Whitespace.pm
- perllib/Open311/Endpoint/Integration/Whitespace.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Whitespace.pm
- t/open311/endpoint/whitespace.t
For https://3.basecamp.com/4020879/buckets/35109031/todolists/7983073165.
More specifically, https://3.basecamp.com/4020879/buckets/35109031/todos/8013810892.
> [Bexley][WW] Container requests post-testing fixes

- perllib/Integrations/Agile.pm
- perllib/Open311/Endpoint/Integration/Agile.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/Agile.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Agile.pm
- t/open311/endpoint/agile.t
- t/open311/endpoint/agile.yml
- t/open311/endpoint/bexley.t
- t/open311/endpoint/uk.t
For https://github.com/mysociety/societyworks/issues/4675.
Config:
```
url: https://integration.stg.agileapplications.co.uk/api/bexley/gardenwaste/external/request
category_mapping:
garden_subscription:
name: Garden Subscription
group: Waste
```
> [WW][Bexley] Agile garden subscription setup

- perllib/Open311/Endpoint/Integration/UK/Bexley/Symology.pm
- t/open311/endpoint/bexley_symology.t
For https://mysocietysupport.freshdesk.com/a/tickets/5048.
> [Bexley] [Symology] Update close codes.

- perllib/Open311/Endpoint/Integration/UK/Bristol/Alloy.pm
- t/open311/endpoint/bristol_alloy.t
- t/open311/endpoint/bristol_alloy.yml
Moving from having all street cleansing categories under one group, to having street cleansing category
in another group.
Specifically, the bike category wants to fit into the main FMS bike category.
> [Bristol][Alloy] Adds extra street cleansing categories

- perllib/Open311/Endpoint/Integration/UK/Bristol/Alloy.pm
- t/open311/endpoint/bristol_alloy.t
- t/open311/endpoint/bristol_alloy.yml
The grep on category code should be an exact match and not a regexp
> [Bristol][Alloy] Quote grep to match category brackets

- perllib/Open311/Endpoint/Integration/Symology.pm
- t/open311/endpoint/files/centralbedfordshire/updates/CSVEXP_01112020_0830.CSV
- t/open311/endpoint/files/centralbedfordshire/updates/CSVEXP_01112020_0930.CSV
- t/open311/endpoint/files/centralbedfordshire/updates/CSVEXP_30102020_1630.CSV
- t/open311/endpoint/files/centralbedfordshire/updates/CSVSUM_01112020.CSV
Otherwise lines with extended chars and all subsequent lines are silently ignored.
For FD-5126
> [Symology] Open update CSVs in binary mode

- perllib/Open311/Endpoint/Integration/ATAK.pm
- perllib/Open311/Endpoint/Integration/UK/CentralBedfordshire/Jadu.pm
Counterpart to https://github.com/mysociety/fixmystreet/pull/5418
> Remove any use of my $x if $foo.

- perllib/Open311/Endpoint/Integration/Echo.pm
- perllib/Open311/Endpoint/Integration/UK/Kingston.pm
- t/open311/endpoint/kingston.t
- t/open311/endpoint/kingston.yml
Includes the change needed for https://github.com/mysociety/societyworks/issues/4828
> [Kingston] Echo updates

- perllib/Open311/Endpoint/Integration/UK/Bexley/Symology.pm
- t/open311/endpoint/bexley_symology.t
https://mysocietysupport.freshdesk.com/a/tickets/5302
> [Bexley][Symology] Handle 'MAJ' code in 'Event Type'.

- perllib/Integrations/WDM.pm
- t/open311/endpoint/oxfordshire_wdm.t
> [Oxfordshire] Add new defect field.

- perllib/Open311/Endpoint/Integration/Passthrough.pm
- perllib/Open311/Endpoint/Integration/UK/BANES/Passthrough.pm
- t/open311/endpoint/banes_passthrough.t
For https://mysocietysupport.freshdesk.com/a/tickets/4727
> [BANES] Use bearer token on update get request.

- conf/council-aberdeenshire_confirm.yml-example
- perllib/Integrations/Confirm.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- perllib/Open311/Endpoint/Integration/UK/Aberdeenshire.pm
- t/integrations/confirm.yml
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm_duped_services.yml
- t/open311/endpoint/confirm_jobs.yml
- t/open311/endpoint/confirm_wrapped.yml
- t/open311/endpoint/uk.t
For https://github.com/mysociety/societyworks/issues/4892
> [Aberdeenshire] Initial Confirm setup

- perllib/Open311/Endpoint.pm
This adds a page listing the council configs and letting you view them. The whole service is internal only, so this would be viewable if on the VPN.
> Add config listing pages.

- perllib/Open311/Endpoint/Integration/AlloyV2.pm
- perllib/Open311/Endpoint/Integration/UK/Gloucester.pm
- t/open311/endpoint/gloucester_alloy.t
- t/open311/endpoint/gloucester_alloy.yml
For https://github.com/mysociety/societyworks/issues/4908.
Most additional questions take a Yes/No answer and we just append this to the report description.
The 'Dead animal' category, however, has answers that map to a specific Alloy attribute and we need to send through the correct code for the given answer.
> [Glos City] Additional questions to send to Alloy

- perllib/Open311/Endpoint/Integration/UK/Gloucester.pm
- t/open311/endpoint/gloucester_alloy.t
- t/open311/endpoint/gloucester_alloy.yml
Done as part of https://github.com/mysociety/societyworks/issues/4889 / https://github.com/mysociety/societyworks/issues/4903
in response to [Litter bin service areas](https://3.basecamp.com/4020879/buckets/38208405/todos/8607850161/edit?replace=true) Basecamp query.
> [Glos City] Update service area mapping

- perllib/Open311/Endpoint/Integration/UK/Aberdeenshire.pm
- t/open311/endpoint/aberdeenshire_defect_attributes.t
- t/open311/endpoint/aberdeenshire_defect_attributes.yml
For https://github.com/mysociety/societyworks/issues/4899 (some useful context & screenshots on that ticket)
> [Aberdeenshire] Include attribute values in descriptions when fetching defects

- perllib/Integrations/AlloyV2.pm
- perllib/Integrations/Confirm.pm
- perllib/Open311/Endpoint/Integration/Confirm.pm
- t/integrations/confirm.t
- t/open311/endpoint/alloyv2.t
- t/open311/endpoint/confirm.t
- t/open311/endpoint/confirm.yml
- t/open311/endpoint/confirm_external_system.yml
Enables category changes to propagate in both directions.
For https://github.com/mysociety/societyworks/issues/5043
> [Confirm] Use GraphQL for fetching enquiries & enquiry updates; support category changing

- perllib/Integrations/Whitespace.pm
- perllib/Open311/Endpoint/Integration/UK/Bexley/Whitespace.pm
- perllib/Open311/Endpoint/Integration/Whitespace.pm
- perllib/Open311/Endpoint/Service/UKCouncil/Whitespace.pm
- t/open311/endpoint/bexley.t
- t/open311/endpoint/whitespace.t
- t/open311/endpoint/whitespace.yml
For https://github.com/mysociety/societyworks/issues/5021
For https://github.com/mysociety/societyworks/issues/5022
> [Bexley] Bulky collection submission

- conf/council-buckinghamshire_cams.yml-example
- perllib/Integrations/Rest.pm
- perllib/Open311/Endpoint/Integration/Cams.pm
- perllib/Open311/Endpoint/Integration/UK/Buckinghamshire/Cams.pm
- t/open311/endpoint/buckinghamshire_cams.t
- t/open311/endpoint/buckinghamshire_cams.yml
- t/open311/endpoint/json/cams/report.json
- t/open311/endpoint/json/cams/updates.json
- t/open311/endpoint/uk.t
Integration between FMS and CAMS Desktop for Buckinghamshire as per the tech specification.
https://docs.google.com/document/d/1X3v_y2TBnbaTqDwMlo-sUwt_8RganhJHge-OXleZS-8/edit?tab=t.0#heading=h.a88nmmw52k7z
https://github.com/mysociety/societyworks/issues/4979
https://github.com/mysociety/societyworks/issues/4980
https://github.com/mysociety/societyworks/issues/5014
https://github.com/mysociety/societyworks/issues/5015
https://github.com/mysociety/societyworks/issues/5013
> Bucks cams integration

- perllib/Open311/Endpoint/Integration/Cams.pm
- t/open311/endpoint/json/cams/report.json
> [Cams] Convert newlines to dots.

- perllib/Open311/Endpoint/Integration/Echo.pm
- perllib/Open311/Endpoint/Integration/UK/Kingston.pm
- perllib/Open311/Endpoint/Integration/UK/Merton/Echo.pm
- perllib/Open311/Endpoint/Integration/UK/Sutton.pm
- perllib/Open311/Endpoint/Role/SLWP.pm
- t/open311/endpoint/merton.t
- t/open311/endpoint/merton.yml
- t/open311/endpoint/merton_echo.t
Changes for https://github.com/mysociety/societyworks/issues/5096
> [Merton] Switch to new Echo instance.
